version: '3.9'

volumes:
  dbdata:

networks:
  localhost:
    driver: bridge

services:
  api:
    restart: always
    build: ..
    ports:
      - 8000:8000
    volumes:
      - .:/home/todo_app
    env_file: .env
    container_name: todo_app_drf_api
    depends_on:
      - db
    links:
      - db
    networks:
      - localhost

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql
    container_name: todo_app_db
    networks:
      - localhost
